// Resolving a cell of the grid into what the rules need.
//
// Owner: workflow W4-G. Three facts are asserted, and each one is a bug the tool would
// otherwise have: the effective terrain of a cleared forest, the ownership resolved
// against the viewer, and a cell of a chunk that has not arrived answering "unknown"
// rather than "unowned grass".

import { describe, expect, it } from 'vitest';
import { resolveCell, resolveCells } from '../cells';
import { makeGrid, STRANGER, VIEWER } from './fixtures';
import { CellOwnership, LandUse, TerrainType, cellKey } from '~/shared/index';

describe('resolveCell', () => {
  it('reports an untouched cell as unowned, unused and of the generated terrain', () => {
    const grid = makeGrid({ terrain: TerrainType.FOREST });
    const cell = resolveCell(grid.reader, 3, 4);
    expect(cell).toEqual({
      cellX: 3,
      cellY: 4,
      terrain: TerrainType.FOREST,
      ownership: CellOwnership.UNOWNED,
      landUse: LandUse.NONE,
      hasStandingTree: false,
      fieldId: null,
      forestPlotId: null,
      buildingId: null,
    });
  });

  it('prefers the override to the generated terrain, as a cleared forest requires', () => {
    // GDD section 10: clearing turns forest into arable ground, and ADR-0021 makes the
    // override the only definition of "effective". Reading the generated byte instead
    // would refuse to plough ground the player has already cleared.
    const grid = makeGrid({ terrain: TerrainType.FOREST });
    grid.set(
      { cellX: 1, cellY: 1 },
      { terrainOverride: TerrainType.GRASS, ownerPlayerId: VIEWER, landUse: LandUse.OWNED },
    );
    expect(resolveCell(grid.reader, 1, 1)?.terrain).toBe(TerrainType.GRASS);
    expect(resolveCell(grid.reader, 2, 1)?.terrain).toBe(TerrainType.FOREST);
  });

  it('resolves ownership against the viewer and not against the row', () => {
    const grid = makeGrid();
    grid.set({ cellX: 0, cellY: 0 }, { ownerPlayerId: VIEWER });
    grid.set({ cellX: 1, cellY: 0 }, { ownerPlayerId: STRANGER });
    expect(resolveCell(grid.reader, 0, 0)?.ownership).toBe(CellOwnership.PLAYER);
    expect(resolveCell(grid.reader, 1, 0)?.ownership).toBe(CellOwnership.OTHER);
  });

  it('carries the identifiers the split and the felling need', () => {
    const grid = makeGrid();
    grid.set(
      { cellX: 2, cellY: 2 },
      { ownerPlayerId: VIEWER, landUse: LandUse.FIELD, fieldId: 'field-7' },
    );
    expect(resolveCell(grid.reader, 2, 2)?.fieldId).toBe('field-7');
  });

  it('answers null for a cell whose chunk is not loaded', () => {
    const grid = makeGrid({ loadedChunks: [{ chunkX: 0, chunkY: 0 }] });
    expect(resolveCell(grid.reader, 1, 1)).not.toBeNull();
    expect(resolveCell(grid.reader, 40, 1)).toBeNull();
  });

  it('resolves a negative coordinate to the last column of the previous chunk', () => {
    const grid = makeGrid({
      loadedChunks: [
        { chunkX: 0, chunkY: 0 },
        { chunkX: -1, chunkY: -1 },
      ],
    });
    grid.set({ cellX: -1, cellY: -1 }, { ownerPlayerId: VIEWER });
    expect(resolveCell(grid.reader, -1, -1)?.ownership).toBe(CellOwnership.PLAYER);
    expect(resolveCell(grid.reader, -2, -1)?.ownership).toBe(CellOwnership.UNOWNED);
  });
});

describe('resolveCells', () => {
  it('keeps the order of the keys and reports the unresolved ones apart', () => {
    const grid = makeGrid({ loadedChunks: [{ chunkX: 0, chunkY: 0 }] });
    const resolution = resolveCells(grid.reader, [cellKey(2, 0), cellKey(40, 0), cellKey(1, 0)]);
    expect(resolution.cells.map((cell) => cell.cellX)).toEqual([2, 1]);
    expect(resolution.unresolved).toEqual([cellKey(40, 0)]);
  });
});
