-- Crop catalogue: from one crop to sixty two.
--
-- This file adds enum values and does nothing else, and that is not tidiness. A value
-- added with ALTER TYPE ... ADD VALUE cannot be used in the transaction that adds it,
-- and Prisma wraps each migration file in one, so any INSERT, DEFAULT or comparison
-- naming a value below would fail here. The tables that use them come two files later.
--
-- Order is the catalogue order of shared/config/crops/. Wheat is already present and
-- keeps its identifier: the balance report and the golden tests are anchored on it.

ALTER TYPE "CropId" ADD VALUE 'MAIZ';
ALTER TYPE "CropId" ADD VALUE 'CEBADA';
ALTER TYPE "CropId" ADD VALUE 'AVENA';
ALTER TYPE "CropId" ADD VALUE 'CENTENO';
ALTER TYPE "CropId" ADD VALUE 'SORGO';
ALTER TYPE "CropId" ADD VALUE 'TRITICALE';
ALTER TYPE "CropId" ADD VALUE 'MIJO';
ALTER TYPE "CropId" ADD VALUE 'QUINOA';
ALTER TYPE "CropId" ADD VALUE 'AMARANTO';
ALTER TYPE "CropId" ADD VALUE 'FRIJOL';
ALTER TYPE "CropId" ADD VALUE 'GARBANZO';
ALTER TYPE "CropId" ADD VALUE 'LENTEJA';
ALTER TYPE "CropId" ADD VALUE 'CHICHARO';
ALTER TYPE "CropId" ADD VALUE 'HABA';
ALTER TYPE "CropId" ADD VALUE 'SOYA';
ALTER TYPE "CropId" ADD VALUE 'CACAHUATE';
ALTER TYPE "CropId" ADD VALUE 'CANOLA';
ALTER TYPE "CropId" ADD VALUE 'GIRASOL';
ALTER TYPE "CropId" ADD VALUE 'AJONJOLI';
ALTER TYPE "CropId" ADD VALUE 'LINAZA';
ALTER TYPE "CropId" ADD VALUE 'MOSTAZA';
ALTER TYPE "CropId" ADD VALUE 'ALGODON';
ALTER TYPE "CropId" ADD VALUE 'TABACO';
ALTER TYPE "CropId" ADD VALUE 'PAPA';
ALTER TYPE "CropId" ADD VALUE 'JICAMA';
ALTER TYPE "CropId" ADD VALUE 'BETABEL';
ALTER TYPE "CropId" ADD VALUE 'ZANAHORIA';
ALTER TYPE "CropId" ADD VALUE 'RABANO';
ALTER TYPE "CropId" ADD VALUE 'CHIRIVIA';
ALTER TYPE "CropId" ADD VALUE 'CEBOLLA';
ALTER TYPE "CropId" ADD VALUE 'AJO';
ALTER TYPE "CropId" ADD VALUE 'LECHUGA';
ALTER TYPE "CropId" ADD VALUE 'ESPINACA';
ALTER TYPE "CropId" ADD VALUE 'ACELGA';
ALTER TYPE "CropId" ADD VALUE 'COL';
ALTER TYPE "CropId" ADD VALUE 'COLIFLOR';
ALTER TYPE "CropId" ADD VALUE 'BROCOLI';
ALTER TYPE "CropId" ADD VALUE 'PEPINO';
ALTER TYPE "CropId" ADD VALUE 'CALABACITA';
ALTER TYPE "CropId" ADD VALUE 'CALABAZA';
ALTER TYPE "CropId" ADD VALUE 'MELON';
ALTER TYPE "CropId" ADD VALUE 'SANDIA';
ALTER TYPE "CropId" ADD VALUE 'BERENJENA';
ALTER TYPE "CropId" ADD VALUE 'TOMATE';
ALTER TYPE "CropId" ADD VALUE 'TOMATILLO';
ALTER TYPE "CropId" ADD VALUE 'CHILE';
ALTER TYPE "CropId" ADD VALUE 'PIMIENTO';
ALTER TYPE "CropId" ADD VALUE 'EJOTE';
ALTER TYPE "CropId" ADD VALUE 'CILANTRO';
ALTER TYPE "CropId" ADD VALUE 'PEREJIL';
ALTER TYPE "CropId" ADD VALUE 'ALBAHACA';
ALTER TYPE "CropId" ADD VALUE 'MANZANILLA';
ALTER TYPE "CropId" ADD VALUE 'CEMPASUCHIL';
ALTER TYPE "CropId" ADD VALUE 'GIRASOL_ORNAMENTAL';
ALTER TYPE "CropId" ADD VALUE 'CRISANTEMO';
ALTER TYPE "CropId" ADD VALUE 'TULIPAN';
ALTER TYPE "CropId" ADD VALUE 'DALIA';
ALTER TYPE "CropId" ADD VALUE 'MAIZ_FORRAJERO';
ALTER TYPE "CropId" ADD VALUE 'SORGO_FORRAJERO';
ALTER TYPE "CropId" ADD VALUE 'AVENA_FORRAJERA';
ALTER TYPE "CropId" ADD VALUE 'CENTENO_FORRAJERO';
