// Decoding a chunk into tile indices, for both layers of the near level of detail.
//
// Owner: workflow W4-D (world rendering). Pure functions over the chunk view: given the
// generated terrain and the modification layer, they produce the two index arrays a
// Phaser tilemap consumes, plus the tint array that carries growth progress.
//
// Everything about the atlases is read from the contract W3-D published (NOTES-w3d,
// "Contrato que esta fase publica"): `terrainTileIndex` for the base layer,
// `usageTileIndex` and `usageTileIndexForCropState` for the upper one, and
// `variantForCell` for the variant. Not one tile index is written as a literal here,
// which is what stops a change of atlas layout from becoming a wrong but plausible
// tile.
//
// Two rules of plan section 9.3 are implemented and not merely respected:
//
//   1. The progress of a growing field travels as a tint and never as more tiles. One
//      tile per state, one tint per cell.
//   2. The variant of a terrain tile is a hash of the cell coordinate folded with the
//      world seed, so the mosaic is identical in two sessions and in two tabs and a
//      chunk that streams back in does not reshuffle.

import { growthTint } from '../textures/palette';
import { variantForCell } from '../textures/prng';
import { TERRAIN_VARIANTS, terrainTileIndex } from '../textures/terrain-atlas';
import { UsageTile, usageTileIndex, usageTileIndexForCropState } from '../textures/usage-atlas';
import { type FieldRenderState, type WorldChunkView } from './source';
import { CropCycleState, LandUse, cellKey, terrainFromCode } from '~/shared/index';

/** Tint that leaves a tile exactly as it was drawn. */
export const NO_TINT = 0xffffff;

/**
 * Index of "no tile here" in the usage layer.
 *
 * Minus one and not the transparent tile of the atlas, and the difference is the whole
 * quad budget: `RunCull` of Phaser skips a tile whose index is -1, whereas a
 * transparent tile is culled in, batched and drawn. On an unmodified chunk that is the
 * difference between 1 024 quads and none, and the usage layer is empty over most of a
 * virtually infinite world.
 */
export const NO_USAGE_TILE = -1;

/** What the usage layer needs beyond the chunk itself. */
export interface UsageContext {
  /** Player the ownership colours are resolved against. */
  readonly viewerPlayerId: string | null;
  /** State of a field, resolved by identifier (ADR-0010). */
  readonly fieldState: (fieldId: string) => FieldRenderState | undefined;
  /** Cells awaiting confirmation, as cell keys (plan section 7). */
  readonly pending: ReadonlySet<number>;
}

/** The two arrays the near level of detail needs, one entry per cell, row major. */
export interface ChunkTileData {
  readonly terrain: Uint16Array;
  /** `NO_USAGE_TILE` where the cell carries no usage tile. */
  readonly usage: Int16Array;
  /** Tint of the usage tile of each cell. `NO_TINT` where none applies. */
  readonly usageTint: Uint32Array;
}

/**
 * Tile indices of the terrain layer.
 *
 * `terrainOverride` wins over the generated byte: it is the cleared forest of GDD
 * section 10, and a cell whose forest was cleared has to read as the terrain it became
 * and not as the terrain the generator still produces for it.
 */
export function terrainTileIndices(
  chunk: WorldChunkView,
  seed: number,
  chunkSize: number,
): Uint16Array {
  const cells = chunkSize * chunkSize;
  const indices = new Uint16Array(cells);
  const originCellX = chunk.chunkX * chunkSize;
  const originCellY = chunk.chunkY * chunkSize;
  for (let idx = 0; idx < cells; idx += 1) {
    const localX = idx % chunkSize;
    const localY = (idx - localX) / chunkSize;
    const cellX = originCellX + localX;
    const cellY = originCellY + localY;
    const override = chunk.patches.get(idx)?.terrainOverride ?? null;
    const terrain = override ?? terrainFromCode(chunk.terrain[idx] ?? 0);
    indices[idx] = terrainTileIndex(terrain, variantForCell(seed, cellX, cellY, TERRAIN_VARIANTS));
  }
  return indices;
}

/**
 * What one modified cell resolves to.
 *
 * Two shapes and not one, because a crop state addresses the atlas through
 * `usageTileIndexForCropState` and everything else through `usageTileIndex`. Keeping
 * them apart is what removes the cast that a single shape would need, and with it the
 * chance of asking for the tile of a state that is not one.
 */
type UsageResolution =
  | { readonly kind: 'CROP'; readonly state: CropCycleState; readonly tint: number }
  | { readonly kind: 'TILE'; readonly tile: UsageTile };

/** The usage tile of one modified cell. */
function usageOfPatch(
  landUse: LandUse,
  ownerPlayerId: string | null,
  fieldId: string | null,
  context: UsageContext,
): UsageResolution {
  switch (landUse) {
    case LandUse.FIELD: {
      const state = fieldId === null ? undefined : context.fieldState(fieldId);
      if (state === undefined) {
        // The field is not in the client state yet: draw it as untouched land inside a
        // field rather than guess a phase, which would show a harvest that never was.
        return { kind: 'TILE', tile: UsageTile.VIRGIN };
      }
      return {
        kind: 'CROP',
        state: state.cropCycleState,
        tint:
          state.cropCycleState === CropCycleState.GROWING
            ? growthTint(state.growthProgressBp)
            : NO_TINT,
      };
    }
    case LandUse.BUILDING:
      return { kind: 'TILE', tile: UsageTile.FARM };
    case LandUse.FOREST_PLOT:
      return { kind: 'TILE', tile: UsageTile.FOREST_PLOT };
    case LandUse.OWNED:
    case LandUse.ROAD:
    case LandUse.NONE:
    default:
      if (ownerPlayerId === null) {
        return { kind: 'TILE', tile: UsageTile.EMPTY };
      }
      return {
        kind: 'TILE',
        tile: ownerPlayerId === context.viewerPlayerId ? UsageTile.OWNED : UsageTile.OWNED_FOREIGN,
      };
  }
}

/**
 * Tile indices and tints of the usage layer.
 *
 * The pending decoration wins over everything, because it says "the server has not
 * answered yet" about that very cell and any other reading of it would be a claim the
 * client is not entitled to make (plan section 7).
 */
export function usageTileIndices(
  chunk: WorldChunkView,
  chunkSize: number,
  context: UsageContext,
): { readonly indices: Int16Array; readonly tints: Uint32Array } {
  const cells = chunkSize * chunkSize;
  const indices = new Int16Array(cells);
  const tints = new Uint32Array(cells);
  const pendingIndex = usageTileIndex(UsageTile.PENDING);
  indices.fill(NO_USAGE_TILE);
  tints.fill(NO_TINT);

  const hasPending = context.pending.size > 0;
  const originCellX = chunk.chunkX * chunkSize;
  const originCellY = chunk.chunkY * chunkSize;

  for (const [idx, patch] of chunk.patches) {
    if (idx < 0 || idx >= cells) {
      continue;
    }
    const resolved = usageOfPatch(patch.landUse, patch.ownerPlayerId, patch.fieldId, context);
    if (resolved.kind === 'CROP') {
      indices[idx] = usageTileIndexForCropState(resolved.state);
      tints[idx] = resolved.tint;
      continue;
    }
    indices[idx] =
      resolved.tile === UsageTile.EMPTY ? NO_USAGE_TILE : usageTileIndex(resolved.tile);
  }

  if (hasPending) {
    for (let idx = 0; idx < cells; idx += 1) {
      const localX = idx % chunkSize;
      const localY = (idx - localX) / chunkSize;
      if (context.pending.has(cellKey(originCellX + localX, originCellY + localY))) {
        indices[idx] = pendingIndex;
        tints[idx] = NO_TINT;
      }
    }
  }

  return { indices, tints };
}

/** Both layers of a chunk in one pass. */
export function chunkTileData(
  chunk: WorldChunkView,
  seed: number,
  chunkSize: number,
  context: UsageContext,
): ChunkTileData {
  const usage = usageTileIndices(chunk, chunkSize, context);
  return {
    terrain: terrainTileIndices(chunk, seed, chunkSize),
    usage: usage.indices,
    usageTint: usage.tints,
  };
}

/**
 * A flat index array as the rows a Phaser tilemap consumes.
 *
 * A copy is unavoidable: `make.tilemap({ data })` wants an array of arrays of numbers
 * and a typed array is neither. It is done once per chunk build, which is the path the
 * 4 ms budget of the brief applies to, and never per frame.
 */
export function toRows(indices: ArrayLike<number>, chunkSize: number): number[][] {
  const rows: number[][] = new Array<number[]>(chunkSize);
  for (let row = 0; row < chunkSize; row += 1) {
    const line: number[] = new Array<number>(chunkSize);
    const offset = row * chunkSize;
    for (let column = 0; column < chunkSize; column += 1) {
      line[column] = indices[offset + column] ?? 0;
    }
    rows[row] = line;
  }
  return rows;
}
