// Resolving a cell of the grid into what the selection rules need.
//
// Owner: workflow W4-G (selection tool).
//
// The tool reads the same decoded chunks the renderer draws, through the same port
// (`game/world/source.ts`), and never through a store: the zone rule forbids it and the
// port is the seam. `WorldSource` satisfies `CellReader` structurally, so a test can
// resolve cells from a handful of chunk fixtures with no Phaser and no Pinia.
//
// Two rules of the domain are applied here and nowhere else in this directory:
//
//   1. The effective terrain is the override when there is one and the generated byte
//      otherwise (ADR-0021, point 2). A caller that read the generated terrain directly
//      would treat a cleared forest as forest and refuse to plough it.
//   2. Ownership is resolved against the viewer, not stored: `PLAYER`, `OTHER` or
//      `UNOWNED`, which is what `shared/rules/selection.ts` asks for and the same
//      resolution `stores/world.ts` does for the panels.
//
// A cell whose chunk is not loaded resolves to null rather than to a guess. That is what
// feeds `unresolvedCount`, and it is the difference between "this cell is invalid" and
// "nothing is known about this cell yet".

import { type WorldChunkView } from '../world/source';
import {
  CellOwnership,
  LandUse,
  cellFromKey,
  cellIndex,
  chunkOf,
  terrainFromCode,
  type SelectionCell,
} from '~/shared/index';

/**
 * A cell as the tool needs it: the shared shape plus the identifiers of what occupies it.
 *
 * `SelectionCell` carries no `fieldId` nor `forestPlotId`, because the six shared
 * purposes never need them. The split of GDD section 21 and the felling of GDD section
 * 135 do: both act against one named subject and have to tell its cells from the cells of
 * the subject next to it.
 */
export interface ToolCell extends SelectionCell {
  readonly fieldId: string | null;
  readonly forestPlotId: string | null;
  readonly buildingId: string | null;
}

/** The part of `WorldSource` the tool reads. Declared structurally, never imported. */
export interface CellReader {
  readonly chunkSize: number;
  chunk(chunkX: number, chunkY: number): WorldChunkView | undefined;
  viewerPlayerId(): string | null;
}

/** The cell at a coordinate, or null when its chunk is not loaded. */
export function resolveCell(reader: CellReader, cellX: number, cellY: number): ToolCell | null {
  const size = reader.chunkSize;
  const chunk = chunkOf(cellX, cellY, size);
  const held = reader.chunk(chunk.chunkX, chunk.chunkY);
  if (held === undefined) {
    return null;
  }
  const idx = cellIndex(cellX, cellY, size);
  const patch = held.patches.get(idx);
  const generated = terrainFromCode(held.terrain[idx] ?? 0);
  if (patch === undefined) {
    return {
      cellX,
      cellY,
      terrain: generated,
      ownership: CellOwnership.UNOWNED,
      landUse: LandUse.NONE,
      hasStandingTree: false,
      fieldId: null,
      forestPlotId: null,
      buildingId: null,
    };
  }
  const viewer = reader.viewerPlayerId();
  return {
    cellX,
    cellY,
    terrain: patch.terrainOverride ?? generated,
    ownership:
      patch.ownerPlayerId === null
        ? CellOwnership.UNOWNED
        : patch.ownerPlayerId === viewer
          ? CellOwnership.PLAYER
          : CellOwnership.OTHER,
    landUse: patch.landUse,
    hasStandingTree: patch.hasStandingTree,
    fieldId: patch.fieldId,
    forestPlotId: patch.forestPlotId,
    buildingId: patch.buildingId,
  };
}

export interface ResolvedSelection {
  /** The cells that could be resolved, in the order of the keys. */
  readonly cells: readonly ToolCell[];
  /** Keys whose chunk is not loaded, in the same order. */
  readonly unresolved: readonly number[];
}

/** Resolves a whole set of cell keys in one pass. */
export function resolveCells(reader: CellReader, keys: Iterable<number>): ResolvedSelection {
  const cells: ToolCell[] = [];
  const unresolved: number[] = [];
  for (const key of keys) {
    const coord = cellFromKey(key);
    const cell = resolveCell(reader, coord.cellX, coord.cellY);
    if (cell === null) {
      unresolved.push(key);
      continue;
    }
    cells.push(cell);
  }
  return { cells, unresolved };
}
