// How a building is named, coloured and described in the interface.
//
// Owner: W4-F. Read by the three farm panels (`farm-overview`, `building-inspector`,
// `building-placement`).
//
// It is presentation and nothing else: every figure it shows comes from
// `BUILDING_CATALOGUE`, so adding a building to `shared/config/buildings.ts` adds it here
// with no edit, and no capacity, footprint or price is ever written as a literal (ADR-0011).
// The capacity of a building is read through `capacityKind` and not through a switch on the
// type, which is the same decision the read model of the server took
// (docs/handoff/NOTES-w4b.md, section 5.4).
//
// The colour is the token of the shared palette, which the canvas draws the same building
// with (`assets/tokens.css`, block generated by W3-D). A panel that invented its own colour
// would make the legend of plan section 9.4 wrong, and the legend is a playability
// requirement in a game whose art is abstract.

import {
  BUILDING_CATALOGUE,
  BuildingType,
  STORAGE_RESOURCE_UNITS,
  type BuildingDefinition,
} from '~/shared/index';

/** Name of each building, in Spanish, as the interface says it. */
export const BUILDING_TYPE_LABELS: Readonly<Record<BuildingType, string>> = {
  // GDD section 26.
  GARAGE: 'Garaje',
  // GDD section 27.
  SILO: 'Silo',
  // GDD section 28.
  WORKER_HOME: 'Vivienda de trabajadores',
  // GDD section 29.
  WORKSHOP: 'Taller',
  // GDD section 136.
  WOOD_STORAGE: 'Almacen de madera',
};

/**
 * Section of the GDD the capacity of each building answers to, shown next to the figure.
 *
 * It is data and not a comment because the reviewer of W7 checks the panels against these
 * numbers, and a section printed on screen is a claim that can be checked.
 */
export const BUILDING_CAPACITY_SECTIONS: Readonly<Record<BuildingType, number>> = {
  GARAGE: 96,
  SILO: 27,
  WORKER_HOME: 108,
  WORKSHOP: 29,
  WOOD_STORAGE: 136,
};

/** Palette token the canvas paints the building with (plan section 9.4). */
export const BUILDING_TYPE_COLOURS: Readonly<Record<BuildingType, string>> = {
  GARAGE: 'var(--fw-building-garage, #5b6570)',
  SILO: 'var(--fw-building-silo, #b6bcc2)',
  WORKER_HOME: 'var(--fw-building-worker-home, #b6a58a)',
  WORKSHOP: 'var(--fw-building-workshop, #7a6a58)',
  WOOD_STORAGE: 'var(--fw-building-wood-storage, #8a6b45)',
};

export function labelOfBuildingType(type: BuildingType): string {
  return BUILDING_TYPE_LABELS[type];
}

export function colourOfBuildingType(type: BuildingType): string {
  return BUILDING_TYPE_COLOURS[type];
}

export function definitionOfBuildingType(type: BuildingType): BuildingDefinition {
  return BUILDING_CATALOGUE[type];
}

/** `6 x 8 celdas`, from the catalogue and never from the row. */
export function footprintTextOf(type: BuildingType): string {
  const definition = BUILDING_CATALOGUE[type];
  return `${definition.widthCells} x ${definition.heightCells} celdas`;
}

/**
 * What the capacity of a building counts, in the unit its kind implies.
 *
 * `units` is the display unit and `value` the figure already divided, so the caller
 * formats with `useFormatting` and this module never formats money or thousands itself.
 */
export interface CapacityReading {
  readonly kind: BuildingDefinition['capacityKind'];
  /** Capacity in the display unit, or null for a building that counts nothing. */
  readonly value: number | null;
  readonly unit: string;
  /** Capacity in the stored unit, which is what a comparison uses. */
  readonly storedUnits: number;
  /** Divisor between the stored unit and the display unit (litres 1, wood 1000). */
  readonly displayDivisor: number;
  readonly gddSection: number;
  /** One line describing what the capacity is for, for a building that counts nothing. */
  readonly note: string | null;
}

export function capacityReadingOf(type: BuildingType): CapacityReading {
  const definition = BUILDING_CATALOGUE[type];
  const section = BUILDING_CAPACITY_SECTIONS[type];
  if (definition.capacityKind === 'NONE' || definition.capacity === null) {
    return {
      kind: definition.capacityKind,
      value: null,
      unit: '',
      storedUnits: 0,
      displayDivisor: 1,
      gddSection: section,
      note: definition.providesRepair ? 'Da acceso a la reparacion de maquinaria.' : null,
    };
  }
  if (definition.capacityKind === 'STORAGE' && definition.capacityResource !== null) {
    const units = STORAGE_RESOURCE_UNITS[definition.capacityResource];
    return {
      kind: definition.capacityKind,
      value: definition.capacity / units.displayDivisor,
      unit: units.displayUnit,
      storedUnits: definition.capacity,
      displayDivisor: units.displayDivisor,
      gddSection: section,
      note: null,
    };
  }
  return {
    kind: definition.capacityKind,
    value: definition.capacity,
    unit: 'plazas',
    storedUnits: definition.capacity,
    displayDivisor: 1,
    gddSection: section,
    note: null,
  };
}

/** What a building of this type holds, or null when it holds nothing fungible. */
export function storageResourceOf(type: BuildingType): BuildingDefinition['capacityResource'] {
  return BUILDING_CATALOGUE[type].capacityResource;
}

/** Whether the occupancy of a building counts machines (GDD section 96). */
export function countsMachines(type: BuildingType): boolean {
  return BUILDING_CATALOGUE[type].capacityKind === 'MACHINES';
}

/** Whether the occupancy of a building counts workers (GDD section 108). */
export function countsWorkers(type: BuildingType): boolean {
  return BUILDING_CATALOGUE[type].capacityKind === 'WORKERS';
}

/** The catalogue in declaration order, which is the order the chooser shows. */
export const BUILDING_TYPE_ORDER: readonly BuildingType[] = [
  BuildingType.GARAGE,
  BuildingType.SILO,
  BuildingType.WORKER_HOME,
  BuildingType.WORKSHOP,
  BuildingType.WOOD_STORAGE,
];
